[theme]
base="light"
primaryColor="#003DFF"
secondaryBackgroundColor="#FFFFFF"
backgroundColor="#FFFFFF"
textColor="#000000"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
hideTopBar = false
wideMode = true
